[package]
name = "burn-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.1", features = ["train", "vision", "cuda", "autodiff", "std", "tui", "metrics"], default-features = false }
